#!/bin/bash

#####################################################
######## AUTO-REAVER CONFIGURATION SETTINGS #########
#####################################################

###### SCRIPT PATHS/FILES ######
REAVER_DIR=$(pwd);
REAVER_SESSION_DIR="$REAVER_DIR/SESSION";
REAVER_TMP_DIR="$REAVER_DIR/TMP";
REAVER_CRACKED_DIR="$REAVER_DIR/CRACKED";
PATH_IEEE="/sys/class/ieee80211/";
PATH_DRIVER="/device/driver/module/drivers/";
PATH_DEVICE="/device/net/";
CRACKED_LIST_FILE="$REAVER_CRACKED_DIR/CrackedList";
DEVICE_LIST_FILE="$REAVER_TMP_DIR/DeviceList";
WASH_LIST_FILE="$REAVER_TMP_DIR/WashList"
MENU_FILE="$REAVER_DIR/menu";
CONFIGURATION_FILE="$REAVER_DIR/configurationSettings";
REAVER_OPTIONS_FILE="$REAVER_DIR/reaverconfiguration";
SESSION_FILE="";
STATUS_FILE="";
###### SCRIPT GLOBAL VARIABLES ######
WIFI_CARD_DRIVER="";
WIFI_CARD_LOGICAL="";
WIFI_CARD_PHY="";
WIFI_CARD_MONITOR="";
AP_BSSID="";
AP_CHANNEL="";
AP_ESSID="";
AP_WPS="";
AP_LOCK="";
WIFI_CARD_RNDMAC="";
BSSID_CLEAR="";
RESCAN_AP=0;
WASH_SCAN=1;
MENU_OUTPUT="";
COUNTMENU="";
MENUCHOICE="";
###### SCRIPT REQUISITES ######
REQUISITES='("reaver" "macchanger" "aircrack-ng" "konsole" "wash" "gawk" "curl" "sed" "mdk3")';
HTTP_CONN="https://www.google.com/";
###### MDK3 ######
MAX_CLIENTS=800000;
MAX_CLIENTS_BREAK=40000;
###### AIREPLAY-NG ######
FAKE_AUTH_DELAY_SECONDS=60;
###### REAVER ######
REAVER_ARGS='("-i " "-b " "-m " "-e " "-c " "-s " "-C " "-f " "-5 none" "-vv none" "-q none" "-p " "-d " "-l " "-g " "-x " "-r " "-t " "-T " "-A none" "-N none" "-S none" "-L none" "-E none" "-J none" "-F none" "-w none" "-K none" "-Z none" "-O ")';
REAVER_PIN_ATTEMPTS=3;
REAVER_ATTEMPT_DELAY=0;
ADDITIONAL_OPTIONS_YN="Yes";
ADDITIONAL_OPTIONS="-E -S -N -T 1 -t 15 --win7";
###### WASH ######
WASH_TIME=20;
MAX_WASH_ATTEMPT=4;
WASH_TIMEOUT=30;
