#!/bin/bash

#####################################################
############ AUTO-REAVER CONFIGURATION ##############
#####################################################

###### APLICATION PATHS ######
REAVER_DIR=$(pwd);
REAVER_SESSION_DIR="$REAVER_DIR/SESSION"
REAVER_TMP_DIR="$REAVER_DIR/TMP"
REAVER_CRACKED_DIR="$REAVER_DIR/CRACKED"
PATH_IEEE="/sys/class/ieee80211/";
PATH_DRIVER="/device/driver/module/drivers/";
PATH_DEVICE="/device/net/";
###### APLICATION GLOBAL VARIABLES ######
WIFI_CARD_DRIVER="";
WIFI_CARD_LOGICAL="";
WIFI_CARD_PHY="";
WIFI_CARD_MONITOR="";
SCRIPT_INIT=0
AP_BSSID="";
AP_CHANNEL="";
AP_ESSID="";
AP_WPS="";
AP_LOCK="";
PROCEED=0;
SESSION_FILE="";
CMD_FAUTH="";
CMD_REAVER="";
REAVER_GET_KEY=0;
WIFI_CARD_RNDMAC="";
BSSID_LIMIT_FILE="";
###### APPLICATION REQUISITES ######
COMMAND="reaver macchanger airmon-ng aireplay-ng konsole"
HTTP_CONN="https://www.google.com/"
###### AIREPLAY-NG ######
FAKE_AUTH_DELAY_SECONDS=60;
###### REAVER OPTIONS ######
REAVER_PIN_ATTEMPTS=3;
REAVER_ATTEMPT_DELAY=0;
ADDITIONAL_OPTIONS_YN="Yes";
ADDITIONAL_OPTIONS="-E -S -N -T 1 -t 15 --win7";
###### WASH SCAN TIME ######
WASH_TIME=25;
